"""Skill summary generation for compact LLM-friendly tool descriptions.

DEV NOTES:
- This is the core value proposition of dietmcp. The skills generator compresses
  ~2000 tokens of JSON schema into ~200 tokens of readable summary.
- The categorization heuristic uses simple keyword matching. It's intentionally
  naive — a more sophisticated approach (e.g., embedding-based clustering) would
  add a dependency and complexity for marginal improvement. The fallback "Tools"
  category catches anything that doesn't match.
- Compact signatures like `search(query: str, ?limit: int)` are generated by
  ToolDefinition.compact_signature(). The `?` prefix for optional params is a
  convention borrowed from TypeScript/Flow that LLMs understand well.
- The _truncate function strips newlines from descriptions because multi-line
  descriptions in a skill summary would break the one-line-per-tool format.
"""

from __future__ import annotations

from dietmcp.cache.tool_cache import ToolCache
from dietmcp.config.loader import DietMcpConfig
from dietmcp.core.discovery import discover_tools
from dietmcp.models.skill import SkillCategory, SkillEntry, SkillSummary
from dietmcp.models.tool import ToolDefinition


# Keyword-to-category mapping for heuristic grouping
_CATEGORY_KEYWORDS: dict[str, list[str]] = {
    "File Operations": ["file", "read", "write", "directory", "path", "rename", "move", "copy", "delete"],
    "Search": ["search", "find", "grep", "query", "filter", "match", "lookup"],
    "Database": ["sql", "database", "table", "row", "column", "schema", "migrate", "insert", "select"],
    "Network": ["http", "request", "fetch", "url", "api", "endpoint", "webhook"],
    "Browser": ["navigate", "click", "screenshot", "page", "element", "browser", "dom"],
    "Git": ["git", "commit", "branch", "merge", "pull", "push", "diff", "repo"],
    "Documentation": ["doc", "readme", "markdown", "comment", "describe"],
}


async def generate_skills(
    server_name: str,
    config: DietMcpConfig,
    force_refresh: bool = False,
    cache: ToolCache | None = None,
) -> SkillSummary:
    """Generate a compact skill summary for an MCP server's tools.

    Fetches tool definitions (from cache or live), groups them by category
    using heuristic keyword matching, and compresses each tool into a
    one-line signature with description.

    Args:
        server_name: Name of the server.
        config: Full application configuration.
        force_refresh: Bypass cache if True.
        cache: Optional cache instance.

    Returns:
        SkillSummary ready for rendering.
    """
    tools = await discover_tools(server_name, config, force_refresh=force_refresh, cache=cache)
    grouped = _categorize_tools(tools)

    categories = tuple(
        SkillCategory(
            name=cat_name,
            tools=tuple(
                SkillEntry(
                    signature=tool.compact_signature(),
                    description=_truncate(tool.description, 80),
                )
                for tool in cat_tools
            ),
        )
        for cat_name, cat_tools in sorted(grouped.items())
    )

    exec_syntax = f"dietmcp exec {server_name} <tool> --args '{{\"key\": \"value\"}}'"

    return SkillSummary(
        server_name=server_name,
        tool_count=len(tools),
        categories=categories,
        exec_syntax=exec_syntax,
    )


def _categorize_tools(tools: list[ToolDefinition]) -> dict[str, list[ToolDefinition]]:
    """Group tools into categories by keyword matching on name + description."""
    groups: dict[str, list[ToolDefinition]] = {}
    uncategorized: list[ToolDefinition] = []

    for tool in tools:
        searchable = f"{tool.name} {tool.description}".lower()
        matched_category = None
        best_score = 0

        for category, keywords in _CATEGORY_KEYWORDS.items():
            score = sum(1 for kw in keywords if kw in searchable)
            if score > best_score:
                best_score = score
                matched_category = category

        if matched_category and best_score > 0:
            groups.setdefault(matched_category, []).append(tool)
        else:
            uncategorized.append(tool)

    if uncategorized:
        groups["Tools"] = uncategorized

    return groups


def _truncate(text: str, max_len: int) -> str:
    """Truncate text to max_len, adding ellipsis if needed."""
    text = text.replace("\n", " ").strip()
    if len(text) <= max_len:
        return text
    return text[: max_len - 3] + "..."
